### ISSUE TITLE
Unable to complete Karnak Escape or enter Walse Tower

### ISSUE THREAD

**Issue by wrjones104** [cleartonic/arch_ffvcd#3]
In a newly generated multiworld, multiple players report being unable to complete Karnak Escape (blocked by flames) or being unable to enter Walse Tower after receiving the key. This was generated on a fresh source AP using v.50. I'm attaching the generation log, current server log and output .zip (with .asm and .txt files removed for the web host).

![image](https://github.com/cleartonic/arch_ffvcd/assets/11080054/45afabb7-aaab-43a2-a8a3-006bf5f49597)
![image](https://github.com/cleartonic/arch_ffvcd/assets/11080054/1309132b-1e81-453e-969f-170db63cb05c)
![image](https://github.com/cleartonic/arch_ffvcd/assets/11080054/08874da0-26a9-4808-bb46-729b135ada32)
![image](https://github.com/cleartonic/arch_ffvcd/assets/11080054/a8f6118f-5792-4635-9ecb-e5b960b321de)

[AP_81167464048578656029_Server Log.txt](https://github.com/cleartonic/arch_ffvcd/files/13977457/AP_81167464048578656029_Server.Log.txt)
[Generate_85438802254760156689_2024_01_17_18_41_12.txt](https://github.com/cleartonic/arch_ffvcd/files/13977431/Generate_85438802254760156689_2024_01_17_18_41_12.txt)
[AP_81167464048578656029.zip](https://github.com/cleartonic/arch_ffvcd/files/13977435/AP_81167464048578656029.zip)

**Comment by ajovano** [comment]
Ran into this myself on 0.54. Had the Walse key and couldn't enter. !getitem on the key didn't help.
[AP_43251974030465520305_Spoiler.txt](https://github.com/cleartonic/arch_ffvcd/files/14329225/AP_43251974030465520305_Spoiler.txt)
[ServerLog.txt](https://github.com/cleartonic/arch_ffvcd/files/14329249/ServerLog.txt)
